name: Deploy to Amazon S3

on:
  push:
    branches:
      - main # this triggers the action whenever I push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. checkout code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3
    
    # 2. login to aws using secrets added in settings
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3. Sync files to S3 bucket
    - name: Sync to S3
      run: | 
        aws s3 sync . s3://my-devops-portfolio-website --delete --exclude ".git/*" --exclude ".github/*"